name: Lint

on: [pull_request]

jobs:
  lint:
    name: Lint & Check Types
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3

      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install dependencies
        run: rm -f .yarnclean && yarn --frozen-lockfile --ignore-engines --ignore-optional --non-interactive --silent --ignore-scripts
        env:
          PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true
          HUSKY_SKIP_INSTALL: true

      - name: Run ESLint
        uses: tj-actions/eslint-changed-files@v13
        with:
          token: ${{secrets.GITHUB_TOKEN}}

      - name: Check types
        run: yarn check-types
